### ISSUE TITLE
No action happens when keyboard shortcut pressed.

### ISSUE THREAD

**Issue by weissazool** [marksands/Aviator#2]
Using Xcode 6.2. Have not tried this plugin with 6.1.

First, it conflicts with the default New -> Window key binding.

So I tried removing the conflicting key binding, removing the plugin, restarting Xcode, and re-installing the plugin. Without the conflicting key binding, cmd-shift-T instead has no result.

Is there any expectation of where the tests will be located either in the directory structure or in the .pbxproj?

**Comment by marksands** [comment]
Thanks for the heads up, @weissazool!

I'm aware the shortcut conflicts with the new window keybinding, but I was familiar with it coming from AppCode and really wanted that as an option. I plan on adding a preferences panel to customize the shortcut key at some point.

As is the case with every Xcode update, plugins are broken until their compatibility UUIDs are updated. Sorry for dropping the ball on that! I'll update that field and make sure that's the issue before closing.

Also, directory structure is not important with your test files. It only searches the project's test target for similarly named files ending with the word `test[s]`.

**Comment by marksands** [comment]
Commit [52f2828](https://github.com/marksands/Aviator/commit/52f2828f4d5ff0f03284f398280ca3e1064e566d) updated to work with Xcode 6.2

**Comment by weissazool** [comment]
Interesting, I didn't know that an update was required for every Xcode version. Good to know - it's working now, so clearly that was indeed the issue.

Thanks!
